arb-dir: lib/l10n/arb
template-arb-file: en.arb
output-localization-file: translations.dart
untranslated-messages-file: untranslated.json
synthetic-package: false
output-dir: lib/l10n/generated
output-class: Translations
nullable-getter: false