name: todo_list_bloc
description: Creating a simple todo list using Bloc
publish_to: none
version: 1.0.0

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: 3.24.0

dependencies:
  bloc: 8.1.4
  flutter_bloc: 8.1.6
  provider: 6.1.2
  shared_preferences: 2.3.1
  equatable: 2.0.5
  uuid: 4.4.2
  meta: 1.15.0
  get_it: 7.7.0
  flutter:
    sdk: flutter

dev_dependencies:
  bloc_test: 9.1.7
  mocktail: 1.0.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
